name: Lint

on:
    push:
        paths:
            - '**.js'
            - '**.ts'
            - '**.tsx'

jobs:
    eslint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Replace .npmrc
              run: echo "${{ secrets.NPM_RC }}" > .npmrc
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - run: yarn install
            - run: yarn lint
